---
abstract: 'Send smoke test results to a server'
author:
  - 'Zev Benjamin, C<< <zev at cpan.org> >>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  HTTP::Server::Simple::CGI: 0
  Test::Dependencies: 0
  Test::HTTP::Server::Simple: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.90'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Test::Chimps::Client
name: Test-Chimps-Client
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Class::Accessor: 0
  Cwd: 0
  File::Path: 2.0
  File::Spec: 0
  File::Temp: 0
  HTTP::Request::Common: 0
  LWP::UserAgent: 0
  Params::Validate: 0
  Scalar::Util: 0
  TAP::Harness::Archive: 0
  YAML::Syck: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.11_01
